version: "3.9"

services:
  backend:
    build: 
      context: ./
      dockerfile: Dockerfile.rails
    command: bash -c "bundle install && rm -f tmp/pids/server.pid && rails s -b '0.0.0.0'"
    working_dir: '/usr/src/app'
    tty: true
    volumes:
      - ./:/usr/src/app
      - ./.docker/bundle:/usr/local/bundle
    environment:
      - HISTFILE=/usr/src/app/log/.bash_history 
      - EDITOR=vim
      - PUID="${UID}"
      - PGID="${GID}"
      - UMASK="${USMAK}"
      - USERNAME="${USERNAME}"
    labels:
      # Ajout dans traefik
      - "traefik.enable=true"
      
      # HTTP
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_URL}`)"
      - "traefik.http.routers.${APP_NAME}.entrypoints=http"

      # HTTPS
      - "traefik.http.routers.${APP_NAME}-secure.service=${APP_NAME}-secure"
      - "traefik.http.routers.${APP_NAME}-secure.rule=Host(`${APP_URL}`)"
      - "traefik.http.routers.${APP_NAME}-secure.entrypoints=https"
      - "traefik.http.routers.${APP_NAME}-secure.tls=true"

      # Redirection
      - "traefik.http.middlewares.${APP_NAME}-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.${APP_NAME}-redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.${APP_NAME}.middlewares=${APP_NAME}-redirect"

      # Port interne
      - "traefik.http.services.${APP_NAME}-secure.loadbalancer.server.port=3000"
    expose:
      - 3000
    networks:
      - app-network

  vscode:
    container_name: vscode-${APP_NAME}
    # image: codercom/code-server
    build: 
      context: ./
      dockerfile: Dockerfile.vscode
    depends_on:
      - backend
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "$HOME/.local:/home/coder/.local"
      - "$HOME/.config:/home/coder/.config"
      - "$PWD:/home/coder/project"
      - ./.docker/bundle:/usr/local/bundle
    environment:
      - TZ=Europe/Paris
      - DOCKER_USER=${USERNAME}
      - USER_PASSWORD=1234
    # user: ${UID_GID}
    labels:
      # Ajout dans traefik
      - "traefik.enable=true"
      
      # HTTP
      - "traefik.http.routers.${APP_VSCODE_NAME}.rule=Host(`${APP_VSCODE_URL}`)"
      - "traefik.http.routers.${APP_VSCODE_NAME}.entrypoints=http"

      # HTTPS
      - "traefik.http.routers.${APP_VSCODE_NAME}-secure.service=${APP_VSCODE_NAME}-secure"
      - "traefik.http.routers.${APP_VSCODE_NAME}-secure.rule=Host(`${APP_VSCODE_URL}`)"
      - "traefik.http.routers.${APP_VSCODE_NAME}-secure.entrypoints=https"
      - "traefik.http.routers.${APP_VSCODE_NAME}-secure.tls=true"
      
      # Redirection
      - "traefik.http.middlewares.${APP_VSCODE_NAME}-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.${APP_VSCODE_NAME}-redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.${APP_VSCODE_NAME}.middlewares=${APP_VSCODE_NAME}-redirect"

      # Port interne
      - "traefik.http.services.${APP_VSCODE_NAME}-secure.loadbalancer.server.port=8080"
    networks:
      - app-network

networks:
  app-network:
    name: ${APP_NETWORK}
    external: true